spring.application.name=UserTaskManagerKeycloak

# Server
server.port=8081

# OIDC Configuration (Spring Security OAuth2 style)
keycloak.realm.name=try2
keycloak.server.url=http://localhost:8080
spring.security.oauth2.client.registration.keycloak.client-id=spring-boot-cli
spring.security.oauth2.client.registration.keycloak.client-secret=3BMPeSuXH3232GYucdvmCRCEo6lUQQi6
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/try2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/try2

# SMTP (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arthirajamurugan0459@gmail.com
spring.mail.password=vgjsaibfgummrgxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


## Keycloak
#keycloak.auth-server-url=http://localhost:8080
#keycloak.realm=springboot-demo
#keycloak.resource=springboot-client
#keycloak.credentials.secret=aORDVG0Kw49iPMg7n115fW3wEL80sjs7
#keycloak.public-client=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=postgres
spring.datasource.password=post0459
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway
#spring.flyway.enabled=false
#spring.flyway.locations=classpath:db/migration
